import { FundDetailDto } from '../fund/dto/fund-detail.dto';

export const fundDetailMockData: FundDetailDto[] = [
  {
    id: '1',
    fundName: 'Alpha Growth Fund',
    code: 'AGF001',
    unitPrice: 1.23,
    currencyCode: 'USD',
    priceDate: '2024-06-01',
    navChange: 0.05,
    navChangePercent: 4.24,
    fundType: 'Equity',
    manager: 'Manulife',
    establishDate: '2015-03-01',
    fundSize: 50000000,
    riskLevel: 'High',
    description: 'A growth-oriented equity fund managed by Manulife.'
  },
  {
    id: '2',
    fundName: 'Beta Income Fund',
    code: 'BIF002',
    unitPrice: 2.34,
    currencyCode: 'USD',
    priceDate: '2024-06-01',
    navChange: -0.02,
    navChangePercent: -0.85,
    fundType: 'Bond',
    manager: 'Manulife',
    establishDate: '2017-06-15',
    fundSize: 30000000,
    riskLevel: 'Medium',
    description: 'A stable income bond fund.'
  },
  {
    id: '3',
    fundName: 'Gamma Equity Fund',
    code: 'GEF003',
    unitPrice: 0.98,
    currencyCode: 'EUR',
    priceDate: '2024-06-01',
    navChange: 0.01,
    navChangePercent: 1.03,
    fundType: 'Equity',
    manager: 'Manulife',
    establishDate: '2018-01-20',
    fundSize: 20000000,
    riskLevel: 'Medium',
    description: 'European equity fund.'
  },
  {
    id: '4',
    fundName: 'Delta Balanced Fund',
    code: 'DBF004',
    unitPrice: 3.21,
    currencyCode: 'USD',
    priceDate: '2024-06-01',
    navChange: 0.10,
    navChangePercent: 3.22,
    fundType: 'Balanced',
    manager: 'Manulife',
    establishDate: '2016-09-10',
    fundSize: 40000000,
    riskLevel: 'Low',
    description: 'Balanced fund for moderate risk.'
  },
  {
    id: '5',
    fundName: 'Epsilon Value Fund',
    code: 'EVF005',
    unitPrice: 1.56,
    currencyCode: 'CNY',
    priceDate: '2024-06-01',
    navChange: -0.03,
    navChangePercent: -1.89,
    fundType: 'Value',
    manager: 'Manulife',
    establishDate: '2019-05-05',
    fundSize: 15000000,
    riskLevel: 'Medium',
    description: 'Value fund focused on Chinese market.'
  },
  {
    id: '6',
    fundName: 'Zeta Opportunity Fund',
    code: 'ZOF006',
    unitPrice: 2.78,
    currencyCode: 'USD',
    priceDate: '2024-06-01',
    navChange: 0.07,
    navChangePercent: 2.58,
    fundType: 'Opportunity',
    manager: 'Manulife',
    establishDate: '2014-11-11',
    fundSize: 60000000,
    riskLevel: 'High',
    description: 'Opportunity fund for aggressive growth.'
  },
  {
    id: '7',
    fundName: 'Eta Global Fund',
    code: 'EGF007',
    unitPrice: 1.11,
    currencyCode: 'EUR',
    priceDate: '2024-06-01',
    navChange: 0.02,
    navChangePercent: 1.83,
    fundType: 'Global',
    manager: 'Manulife',
    establishDate: '2013-07-07',
    fundSize: 70000000,
    riskLevel: 'Medium',
    description: 'Global diversified fund.'
  },
  {
    id: '8',
    fundName: 'Theta Dividend Fund',
    code: 'TDF008',
    unitPrice: 2.45,
    currencyCode: 'USD',
    priceDate: '2024-06-01',
    navChange: -0.01,
    navChangePercent: -0.41,
    fundType: 'Dividend',
    manager: 'Manulife',
    establishDate: '2012-02-02',
    fundSize: 80000000,
    riskLevel: 'Low',
    description: 'Dividend fund for stable returns.'
  },
  {
    id: '9',
    fundName: 'Iota Index Fund',
    code: 'IIF009',
    unitPrice: 0.87,
    currencyCode: 'CNY',
    priceDate: '2024-06-01',
    navChange: 0.03,
    navChangePercent: 3.57,
    fundType: 'Index',
    manager: 'Manulife',
    establishDate: '2020-10-10',
    fundSize: 9000000,
    riskLevel: 'Low',
    description: 'Index tracking fund.'
  },
  {
    id: '10',
    fundName: 'Kappa Sector Fund',
    code: 'KSF010',
    unitPrice: 1.99,
    currencyCode: 'USD',
    priceDate: '2024-06-01',
    navChange: 0.04,
    navChangePercent: 2.05,
    fundType: 'Sector',
    manager: 'Manulife',
    establishDate: '2011-01-01',
    fundSize: 100000000,
    riskLevel: 'Medium',
    description: 'Sector focused fund.'
  },
];
